In [47]:
import pandas as pd
import os
import numpy as np

In [48]:
df=pd.read_pickle("data/ball_df.pkl")

In [49]:
type(df)

pandas.core.frame.DataFrame

In [50]:
df['batting_team'].unique()

array(['Australia', 'Hong Kong', 'Zimbabwe', 'India', 'Bangladesh',
       'New Zealand', 'South Africa', 'England', 'West Indies',
       'Pakistan', 'Scotland', 'Oman', 'Ireland', 'Papua New Guinea',
       'United Arab Emirates', 'Sri Lanka', 'Netherlands', 'Nepal',
       'Vanuatu', 'Philippines', 'United States of America', 'Germany',
       'Ghana', 'Uganda', 'Kenya', 'Namibia', 'Nigeria', 'Botswana',
       'Guernsey', 'Denmark', 'Jersey', 'Italy', 'Norway', 'Thailand',
       'Malaysia', 'Maldives', 'Singapore', 'Kuwait', 'Bermuda', 'Canada',
       'Cayman Islands', 'Portugal', 'Gibraltar', 'Spain', 'Bhutan',
       'Qatar', 'Iran', 'Belgium', 'Isle of Man', 'Bulgaria', 'Romania',
       'Luxembourg', 'Austria', 'Czech Republic', 'Greece', 'Serbia',
       'Malta', 'France', 'Sweden', 'Rwanda', 'Finland', 'Hungary',
       'Estonia', 'Cyprus', 'Switzerland', 'Seychelles', 'Malawi',
       'Lesotho', 'Swaziland', 'Tanzania', 'Mozambique', 'Sierra Leone',
       'Cameroon', 'Bahrain', 'Belize', 'Bahamas', 'Argentina', 'Panama',
       'Israel', 'Croatia', 'Turkey', 'Slovenia', 'Cook Islands', 'Samoa',
       'Fiji', 'Japan', 'Indonesia', 'South Korea', 'Mali', 'St Helena',
       'Gambia', 'Eswatini', 'Saudi Arabia', 'China', 'Myanmar', 'Chile',
       'Mexico', 'Cambodia', 'Costa Rica', 'Mongolia', 'Brazil',
       'Ivory Coast', 'Suriname', 'Turks and Caicos Island',
       'Timor-Leste'], dtype=object)

In [51]:
valid_teams=['Pakistan',
 'India',
 'New Zealand',
 'South Africa',
 'West Indies',
 'Sri Lanka',
 'Bangladesh',
 'Zimbabwe',
 'England',
 'Australia']

# Select only specific teams

In [52]:
df=df[
    df['batting_team'].isin(valid_teams) &
    df['bowling_team'].isin(valid_teams)
].copy()

In [53]:
df.head()

,match_id,batting_team,bowling_team,batsman,bowler,ball,runs,wicket,city,venue
0,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.1,0,0,None,Melbourne Cricket Ground
1,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.2,0,0,None,Melbourne Cricket Ground
2,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.3,1,0,None,Melbourne Cricket Ground
3,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.4,2,0,None,Melbourne Cricket Ground
4,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.5,0,0,None,Melbourne Cricket Ground

In [54]:
df.shape

(117957, 10)

# Sort the data by match_id and ball
because we need to calculate cumilative sum and other things which will work only if the data is sorted

Group rows by match, and within each match, order the balls in sequence

In [55]:
df=df.sort_values(
    by=['match_id','ball']
).reset_index(drop=True)

In [56]:
df

,match_id,batting_team,bowling_team,batsman,bowler,ball,runs,wicket,city,venue
0,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.1,0,0,None,Melbourne Cricket Ground
1,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.2,0,0,None,Melbourne Cricket Ground
2,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.3,1,0,None,Melbourne Cricket Ground
3,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.4,2,0,None,Melbourne Cricket Ground
4,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.5,0,0,None,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...,...,...
117952,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.3,1,0,Colombo,R Premadasa Stadium
117953,995469,Sri Lanka,Australia,DM de Silva,MA Starc,19.4,0,0,Colombo,R Premadasa Stadium
117954,995469,Sri Lanka,Australia,DM de Silva,MA Starc,19.5,0,1,Colombo,R Premadasa Stadium
117955,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.6,2,0,Colombo,R Premadasa Stadium
117956,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.7,1,0,Colombo,R Premadasa Stadium

# Processing city
there are many rows with city as null so for that particular rows we will extract the city from the venue
And also there are many cities where only 1 match is played so we will be removing that match from the data for better recommendations.
We will consider only the cities where at least 5 matches are played so approx 5x120=600 balls are bowled

In [57]:
df.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
batsman             0
bowler              0
ball                0
runs                0
wicket              0
city            11276
venue               0
dtype: int64

In [58]:
df[df['city'].isnull()]['venue'].value_counts()

venue
Dubai International Cricket Stadium        3092
Harare Sports Club                         2731
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                   1453
Sydney Cricket Ground                       749
Adelaide Oval                               498
Rawalpindi Cricket Stadium                  368
Sylhet International Cricket Stadium        128
Sharjah Cricket Stadium                     127
Carrara Oval                                 64
Name: count, dtype: int64

In [59]:
cities=np.where(df['city'].isnull(),df['venue'].str.split().apply(lambda x:x[0]),df['city'])

In [60]:
df['city']=cities

In [61]:
df.head()

,match_id,batting_team,bowling_team,batsman,bowler,ball,runs,wicket,city,venue
0,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.1,0,0,Melbourne,Melbourne Cricket Ground
1,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.2,0,0,Melbourne,Melbourne Cricket Ground
2,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.3,1,0,Melbourne,Melbourne Cricket Ground
3,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.4,2,0,Melbourne,Melbourne Cricket Ground
4,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.5,0,0,Melbourne,Melbourne Cricket Ground

In [62]:
df.isnull().sum()

match_id        0
batting_team    0
bowling_team    0
batsman         0
bowler          0
ball            0
runs            0
wicket          0
city            0
venue           0
dtype: int64

In [63]:
df.drop(columns=['venue'],inplace=True)

In [64]:
df.head()

,match_id,batting_team,bowling_team,batsman,bowler,ball,runs,wicket,city
0,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.1,0,0,Melbourne
1,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.2,0,0,Melbourne
2,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.3,1,0,Melbourne
3,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.4,2,0,Melbourne
4,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.5,0,0,Melbourne

In [65]:
df['city'].value_counts()

city
Dubai           5758
Harare          5701
Colombo         5377
Johannesburg    3964
Auckland        3694
                ...
Nairobi          123
Kimberley        123
Dallas           122
Cairns           122
Gwalior          121
Name: count, Length: 111, dtype: int64

In [66]:
city_count=df['city'].value_counts()
city_count=city_count[city_count>599]
valid_cities=city_count.index.tolist()

df=df[df['city'].isin(valid_cities)].copy()
df

,match_id,batting_team,bowling_team,batsman,bowler,ball,runs,wicket,city
0,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.1,0,0,Melbourne
1,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.2,0,0,Melbourne
2,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.3,1,0,Melbourne
3,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.4,2,0,Melbourne
4,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.5,0,0,Melbourne
...,...,...,...,...,...,...,...,...,...
117952,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.3,1,0,Colombo
117953,995469,Sri Lanka,Australia,DM de Silva,MA Starc,19.4,0,0,Colombo
117954,995469,Sri Lanka,Australia,DM de Silva,MA Starc,19.5,0,1,Colombo
117955,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.6,2,0,Colombo
117956,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.7,1,0,Colombo

In [67]:
df['city'].unique()

array(['Melbourne', 'Adelaide', 'Harare', 'Napier', 'Mount Maunganui',
       'Auckland', 'Southampton', 'Cardiff', 'Chester-le-Street',
       'Nagpur', 'Bangalore', 'Lauderhill', 'Dubai', 'Abu Dhabi',
       'Sydney', 'Hobart', 'Wellington', 'Hamilton', 'Barbados',
       'Trinidad', 'Colombo', 'Birmingham', 'Manchester', 'Bristol',
       'Delhi', 'Rajkot', 'Lahore', 'Johannesburg', 'Centurion',
       'Cape Town', 'Mumbai', 'Dhaka', 'Sylhet', 'Karachi', 'Brisbane',
       'Kolkata', 'Gros Islet', 'Basseterre', 'Canberra', 'Perth',
       'Durban', 'Chandigarh', 'Christchurch', 'Providence', 'Kandy',
       'Chattogram', 'Pune', 'Rawalpindi', 'Nottingham', 'Ahmedabad',
       'Bridgetown', "St George's", 'Sharjah', 'Tarouba', 'Kingston',
       'London', 'Dambulla', 'St Lucia', 'Pallekele', 'Mirpur',
       'Hambantota', 'Chittagong'], dtype=object)

# Calculate current runs(cummelative runs)

In [68]:
df["current_score"]=(
    df.groupby("match_id")["runs"].cumsum()
)

In [69]:
df.head()

,match_id,batting_team,bowling_team,batsman,bowler,ball,runs,wicket,city,current_score
0,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.1,0,0,Melbourne,0
1,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.2,0,0,Melbourne,0
2,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.3,1,0,Melbourne,1
3,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.4,2,0,Melbourne,3
4,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.5,0,0,Melbourne,3

# Calculate wickets fallen and wickets left

In [70]:
df['wickets_fallen']=(
    df.groupby('match_id')['wicket'].cumsum()
)

In [71]:
df['wickets_left']=10-df['wickets_fallen']

In [72]:
df.head()

,match_id,batting_team,bowling_team,batsman,bowler,ball,runs,wicket,city,current_score,wickets_fallen,wickets_left
0,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.1,0,0,Melbourne,0,0,10
1,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.2,0,0,Melbourne,0,0,10
2,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.3,1,0,Melbourne,1,0,10
3,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.4,2,0,Melbourne,3,0,10
4,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.5,0,0,Melbourne,3,0,10

# Calculating balls left

In [73]:
df['ball_number']=(
    df['ball'].astype(str).str.split(".").str[0].astype(int)*6+
    df['ball'].astype(str).str.split(".").str[1].astype(int)
)

In [74]:
df['balls_left']=120-df['ball_number']
df['balls_left']=df['balls_left'].apply(lambda x:0 if x<0 else x)

In [75]:
df

,match_id,batting_team,bowling_team,batsman,bowler,ball,runs,wicket,city,current_score,wickets_fallen,wickets_left,ball_number,balls_left
0,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.1,0,0,Melbourne,0,0,10,1,119
1,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.2,0,0,Melbourne,0,0,10,2,118
2,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.3,1,0,Melbourne,1,0,10,3,117
3,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.4,2,0,Melbourne,3,0,10,4,116
4,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.5,0,0,Melbourne,3,0,10,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117952,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.3,1,0,Colombo,125,8,2,117,3
117953,995469,Sri Lanka,Australia,DM de Silva,MA Starc,19.4,0,0,Colombo,125,8,2,118,2
117954,995469,Sri Lanka,Australia,DM de Silva,MA Starc,19.5,0,1,Colombo,125,9,1,119,1
117955,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.6,2,0,Colombo,127,9,1,120,0
117956,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.7,1,0,Colombo,128,9,1,121,0

# Calculating current run rate

In [76]:
df['crr']=df['current_score']/(df['ball_number']/6)

In [77]:
df

,match_id,batting_team,bowling_team,batsman,bowler,ball,runs,wicket,city,current_score,wickets_fallen,wickets_left,ball_number,balls_left,crr
0,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.1,0,0,Melbourne,0,0,10,1,119,0.000000
1,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.2,0,0,Melbourne,0,0,10,2,118,0.000000
2,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.3,1,0,Melbourne,1,0,10,3,117,2.000000
3,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.4,2,0,Melbourne,3,0,10,4,116,4.500000
4,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.5,0,0,Melbourne,3,0,10,5,115,3.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117952,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.3,1,0,Colombo,125,8,2,117,3,6.410256
117953,995469,Sri Lanka,Australia,DM de Silva,MA Starc,19.4,0,0,Colombo,125,8,2,118,2,6.355932
117954,995469,Sri Lanka,Australia,DM de Silva,MA Starc,19.5,0,1,Colombo,125,9,1,119,1,6.302521
117955,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.6,2,0,Colombo,127,9,1,120,0,6.350000
117956,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.7,1,0,Colombo,128,9,1,121,0,6.347107

# Calculating last 5 overs runs

In [78]:
df['last_five_overs_runs']=(
    df.groupby('match_id')['runs']
    .rolling(window=30)
    .sum()
    .reset_index(level=0,drop=True)
)

In [79]:
df.head(50)

,match_id,batting_team,bowling_team,batsman,bowler,ball,runs,wicket,city,current_score,wickets_fallen,wickets_left,ball_number,balls_left,crr,last_five_overs_runs
0,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.1,0,0,Melbourne,0,0,10,1,119,0.000000,NaN
1,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.2,0,0,Melbourne,0,0,10,2,118,0.000000,NaN
2,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.3,1,0,Melbourne,1,0,10,3,117,2.000000,NaN
3,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.4,2,0,Melbourne,3,0,10,4,116,4.500000,NaN
4,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.5,0,0,Melbourne,3,0,10,5,115,3.600000,NaN
5,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.6,3,0,Melbourne,6,0,10,6,114,6.000000,NaN
6,1001349,Australia,Sri Lanka,M Klinger,KMDN Kulasekara,1.1,0,0,Melbourne,6,0,10,7,113,5.142857,NaN
7,1001349,Australia,Sri Lanka,M Klinger,KMDN Kulasekara,1.2,1,0,Melbourne,7,0,10,8,112,5.250000,NaN
8,1001349,Australia,Sri Lanka,AJ Finch,KMDN Kulasekara,1.3,0,0,Melbourne,7,0,10,9,111,4.666667,NaN
9,1001349,Australia,Sri Lanka,AJ Finch,KMDN Kulasekara,1.4,0,0,Melbourne,7,0,10,10,110,4.200000,NaN
10,1001349,Australia,Sri Lanka,AJ Finch,KMDN Kulasekara,1.5,4,0,Melbourne,11,0,10,11,109,6.000000,NaN
11,1001349,Australia,Sri Lanka,AJ Finch,KMDN Kulasekara,1.6,2,0,Melbourne,13,0,10,12,108,6.500000,NaN
12,1001349,Australia,Sri Lanka,M Klinger,JRMVB Sanjaya,2.1,1,0,Melbourne,14,0,10,13,107,6.461538,NaN
13,1001349,Australia,Sri Lanka,AJ Finch,JRMVB Sanjaya,2.2,1,0,Melbourne,15,0,10,14,106,6.428571,NaN
14,1001349,Australia,Sri Lanka,M Klinger,JRMVB Sanjaya,2.3,0,0,Melbourne,15,0,10,15,105,6.000000,NaN
15,1001349,Australia,Sri Lanka,M Klinger,JRMVB Sanjaya,2.4,0,0,Melbourne,15,0,10,16,104,5.625000,NaN
16,1001349,Australia,Sri Lanka,M Klinger,JRMVB Sanjaya,2.5,4,0,Melbourne,19,0,10,17,103,6.705882,NaN
17,1001349,Australia,Sri Lanka,M Klinger,JRMVB Sanjaya,2.6,0,0,Melbourne,19,0,10,18,102,6.333333,NaN
18,1001349,Australia,Sri Lanka,AJ Finch,KMDN Kulasekara,3.1,0,0,Melbourne,19,0,10,19,101,6.000000,NaN
19,1001349,Australia,Sri Lanka,AJ Finch,KMDN Kulasekara,3.2,1,0,Melbourne,20,0,10,20,100,6.000000,NaN
20,1001349,Australia,Sri Lanka,M Klinger,KMDN Kulasekara,3.3,1,0,Melbourne,21,0,10,21,99,6.000000,NaN
21,1001349,Australia,Sri Lanka,AJ Finch,KMDN Kulasekara,3.4,1,0,Melbourne,22,0,10,22,98,6.000000,NaN
22,1001349,Australia,Sri Lanka,M Klinger,KMDN Kulasekara,3.5,4,0,Melbourne,26,0,10,23,97,6.782609,NaN
23,1001349,Australia,Sri Lanka,M Klinger,KMDN Kulasekara,3.6,1,0,Melbourne,27,0,10,24,96,6.750000,NaN
24,1001349,Australia,Sri Lanka,M Klinger,JRMVB Sanjaya,4.1,3,0,Melbourne,30,0,10,25,95,7.200000,NaN
25,1001349,Australia,Sri Lanka,AJ Finch,JRMVB Sanjaya,4.2,3,0,Melbourne,33,0,10,26,94,7.615385,NaN
26,1001349,Australia,Sri Lanka,M Klinger,JRMVB Sanjaya,4.3,4,0,Melbourne,37,0,10,27,93,8.222222,NaN
27,1001349,Australia,Sri Lanka,M Klinger,JRMVB Sanjaya,4.4,4,0,Melbourne,41,0,10,28,92,8.785714,NaN
28,1001349,Australia,Sri Lanka,M Klinger,JRMVB Sanjaya,4.5,1,0,Melbourne,42,0,10,29,91,8.689655,NaN
29,1001349,Australia,Sri Lanka,AJ Finch,JRMVB Sanjaya,4.6,1,0,Melbourne,43,0,10,30,90,8.600000,43.0
30,1001349,Australia,Sri Lanka,AJ Finch,S Prasanna,5.1,1,0,Melbourne,44,0,10,31,89,8.516129,44.0
31,1001349,Australia,Sri Lanka,M Klinger,S Prasanna,5.2,1,0,Melbourne,45,0,10,32,88,8.437500,45.0
32,1001349,Australia,Sri Lanka,M Klinger,S Prasanna,5.3,0,0,Melbourne,45,0,10,33,87,8.181818,44.0
33,1001349,Australia,Sri Lanka,M Klinger,S Prasanna,5.4,0,0,Melbourne,45,0,10,34,86,7.941176,42.0
34,1001349,Australia,Sri Lanka,M Klinger,S Prasanna,5.5,1,0,Melbourne,46,0,10,35,85,7.885714,43.0
35,1001349,Australia,Sri Lanka,AJ Finch,S Prasanna,5.6,1,0,Melbourne,47,0,10,36,84,7.833333,41.0
36,1001349,Australia,Sri Lanka,M Klinger,S Prasanna,5.7,0,0,Melbourne,47,0,10,37,83,7.621622,41.0
37,1001349,Australia,Sri Lanka,AJ Finch,PADLR Sandakan,6.1,1,0,Melbourne,48,0,10,37,83,7.783784,41.0
38,1001349,Australia,Sri Lanka,M Klinger,PADLR Sandakan,6.2,1,0,Melbourne,49,0,10,38,82,7.736842,42.0
39,1001349,Australia,Sri Lanka,AJ Finch,PADLR Sandakan,6.3,0,0,Melbourne,49,0,10,39,81,7.538462,42.0
40,1001349,Australia,Sri Lanka,AJ Finch,PADLR Sandakan,6.4,1,0,Melbourne,50,0,10,40,80,7.500000,39.0
41,1001349,Australia,Sri Lanka,M Klinger,PADLR Sandakan,6.5,1,0,Melbourne,51,0,10,41,79,7.463415,38.0
42,1001349,Australia,Sri Lanka,AJ Finch,PADLR Sandakan,6.6,2,0,Melbourne,53,0,10,42,78,7.571429,39.0
43,1001349,Australia,Sri Lanka,M Klinger,S Prasanna,7.1,0,0,Melbourne,53,0,10,43,77,7.395349,38.0
44,1001349,Australia,Sri Lanka,M Klinger,S Prasanna,7.2,1,0,Melbourne,54,0,10,44,76,7.363636,39.0
45,1001349,Australia,Sri Lanka,AJ Finch,S Prasanna,7.3,1,0,Melbourne,55,0,10,45,75,7.333333,40.0
46,1001349,Australia,Sri Lanka,M Klinger,S Prasanna,7.4,1,0,Melbourne,56,0,10,46,74,7.304348,37.0
47,1001349,Australia,Sri Lanka,AJ Finch,S Prasanna,7.5,4,0,Melbourne,60,0,10,47,73,7.659574,41.0
48,1001349,Australia,Sri Lanka,AJ Finch,S Prasanna,7.6,1,0,Melbourne,61,0,10,48,72,7.625000,42.0
49,1001349,Australia,Sri Lanka,AJ Finch,PADLR Sandakan,8.1,1,0,Melbourne,62,0,10,49,71,7.591837,42.0

# Calculating final score

In [80]:
df['final_score']=(
    df.groupby('match_id')['runs']
    .transform('sum')
)
df

,match_id,batting_team,bowling_team,batsman,bowler,ball,runs,wicket,city,current_score,wickets_fallen,wickets_left,ball_number,balls_left,crr,last_five_overs_runs,final_score
0,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.1,0,0,Melbourne,0,0,10,1,119,0.000000,NaN,168
1,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.2,0,0,Melbourne,0,0,10,2,118,0.000000,NaN,168
2,1001349,Australia,Sri Lanka,AJ Finch,SL Malinga,0.3,1,0,Melbourne,1,0,10,3,117,2.000000,NaN,168
3,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.4,2,0,Melbourne,3,0,10,4,116,4.500000,NaN,168
4,1001349,Australia,Sri Lanka,M Klinger,SL Malinga,0.5,0,0,Melbourne,3,0,10,5,115,3.600000,NaN,168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117952,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.3,1,0,Colombo,125,8,2,117,3,6.410256,32.0,128
117953,995469,Sri Lanka,Australia,DM de Silva,MA Starc,19.4,0,0,Colombo,125,8,2,118,2,6.355932,32.0,128
117954,995469,Sri Lanka,Australia,DM de Silva,MA Starc,19.5,0,1,Colombo,125,9,1,119,1,6.302521,32.0,128
117955,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.6,2,0,Colombo,127,9,1,120,0,6.350000,33.0,128
117956,995469,Sri Lanka,Australia,SMSM Senanayake,MA Starc,19.7,1,0,Colombo,128,9,1,121,0,6.347107,32.0,128

# Droping null values for last 5 overs

In [81]:
df.isnull().sum()

match_id                    0
batting_team                0
bowling_team                0
batsman                     0
bowler                      0
ball                        0
runs                        0
wicket                      0
city                        0
current_score               0
wickets_fallen              0
wickets_left                0
ball_number                 0
balls_left                  0
crr                         0
last_five_overs_runs    24734
final_score                 0
dtype: int64

In [82]:
df.shape

(103614, 17)

In [83]:
df.dropna(inplace=True)

In [84]:
df.isnull().sum()

match_id                0
batting_team            0
bowling_team            0
batsman                 0
bowler                  0
ball                    0
runs                    0
wicket                  0
city                    0
current_score           0
wickets_fallen          0
wickets_left            0
ball_number             0
balls_left              0
crr                     0
last_five_overs_runs    0
final_score             0
dtype: int64

In [85]:
df.shape

(78880, 17)

In [86]:
df=df[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','crr','last_five_overs_runs','final_score']]

In [87]:
df.reset_index(drop=True)

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five_overs_runs,final_score
0,Australia,Sri Lanka,Melbourne,43,90,10,8.600000,43.0,168
1,Australia,Sri Lanka,Melbourne,44,89,10,8.516129,44.0,168
2,Australia,Sri Lanka,Melbourne,45,88,10,8.437500,45.0,168
3,Australia,Sri Lanka,Melbourne,45,87,10,8.181818,44.0,168
4,Australia,Sri Lanka,Melbourne,45,86,10,7.941176,42.0,168
...,...,...,...,...,...,...,...,...,...
78875,Sri Lanka,Australia,Colombo,125,3,2,6.410256,32.0,128
78876,Sri Lanka,Australia,Colombo,125,2,2,6.355932,32.0,128
78877,Sri Lanka,Australia,Colombo,125,1,1,6.302521,32.0,128
78878,Sri Lanka,Australia,Colombo,127,0,1,6.350000,33.0,128
78879,Sri Lanka,Australia,Colombo,128,0,1,6.347107,32.0,128

# Shuffling the data to avoid baised predictions

In [88]:
df=df.sample(df.shape[0]).reset_index(drop=True)

In [89]:
final_df=df.copy()

In [90]:
final_df

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five_overs_runs,final_score
0,Australia,New Zealand,Perth,113,39,7,8.370370,48.0,186
1,New Zealand,England,Hamilton,178,4,5,9.206897,53.0,192
2,India,West Indies,Lauderhill,126,30,8,8.400000,48.0,167
3,Pakistan,South Africa,Nottingham,49,79,8,7.170732,31.0,149
4,Zimbabwe,New Zealand,Hamilton,101,58,9,9.774194,49.0,200
...,...,...,...,...,...,...,...,...,...
78875,England,India,Kolkata,65,73,6,8.297872,48.0,132
78876,Pakistan,Sri Lanka,Colombo,116,29,7,7.648352,42.0,175
78877,West Indies,India,Mirpur,122,0,3,6.100000,40.0,129
78878,South Africa,Australia,Centurion,84,39,7,6.222222,25.0,156
78879,Bangladesh,Zimbabwe,Brisbane,55,70,8,6.600000,37.0,150

In [91]:
final_df.head()
final_df.tail()
final_df.shape

(78880, 9)

In [92]:
#os.makedirs("data",exist_ok=True)
#final_df.to_pickle("data/final_df.pkl")